In [2]:
#numpyライブラリーの読み込み
import numpy  as np

#小数第3位まで表示という意味
%precision 3

'%.3f'

配列操作

In [3]:
#配列の作成
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [4]:
#データ型
data.dtype

dtype('int32')

In [5]:
#次元数と要素数
print('次元数:', data.ndim)
print('要素数:', data.size)

次元数: 1
要素数: 10


In [6]:
#配列の計算(numpy)
data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [7]:
#要素同士での計算
print('掛け算:',np.array([1,2,3,4,5,6,7,8,9,10]) * np.array([10,9,8,7,6,5,4,3,2,1]))
print('累乗:',np.array([1,2,3,4,5,6,7,8,9,10]) ** 2)
print('割り算:',np.array([1,2,3,4,5,6,7,8,9,10]) / np.array([10,9,8,7,6,5,4,3,2,1]))

掛け算: [10 18 24 28 30 30 28 24 18 10]
累乗: [  1   4   9  16  25  36  49  64  81 100]
割り算: [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]


In [8]:
#並び替え(ソート)
print('そのまま:',data)
data.sort()
print('ソート後:',data)

そのまま: [ 9  2  3  4 10  6  7  8  1  5]
ソート後: [ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#スライス; [n:m:s]は「n番目からm-1番目を、sずつ飛ばして取り出す」の意味
#[::-1]は末尾から一つずつ取り出す
data[::-1].sort()
print('ソート後', data)

ソート後 [10  9  8  7  6  5  4  3  2  1]


In [10]:
#最小値
print('Min:',data.min())
#最大値
print('Max:',data.max())
#合計
print('Sum:',data.sum())
#積み上げ
print('Cum:',data.cumsum())
#積み上げ割合
print('Ratio:',data.cumsum() / data.sum())

Min: 1
Max: 10
Sum: 55
Cum: [10 19 27 34 40 45 49 52 54 55]
Ratio: [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


乱数

In [13]:
import numpy.random as random

random.seed(0)

#正規分布(平均０、分散１)の乱数を１０個発生
rnd_data = random.randn(10)

print('乱数10この配列:', rnd_data)

乱数10この配列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [14]:
#抽出対象データ
data = np.array([9,2,3,4,10,6,7,8,1,5])

#ランダム抽出

#10個を抽出(重複あり、復元抽出)
print(random.choice(data, 10))

#10個を抽出(重複なし、非復元抽出)
print(random.choice(data, 10, replace = False))

[ 7  8  8  1  2  6  5  1  5 10]
[10  2  7  8  3  1  6  5  9  4]


↑seedによって乱数が異なる

行列

In [15]:
#0から8までの整数を発生
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
#reshapeで3×3の行列に分割
array1 = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#[行範囲,列範囲]
#1行目
print(array1[0,:])
#1列目
print(array1[:,0])

[0 1 2]
[0 3 6]


In [19]:
#行列の計算
array2 = np.arange(9,18).reshape(3,3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [20]:
#行列の積
np.dot(array1,array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [21]:
#要素同士の積
array1 * array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [22]:
#要素が０や１の行列を作る
print(np.zeros((2,3), dtype = np.int64))
print(np.ones((2,3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
