In [3]:
#線形代数用のライブラリ
import scipy.linalg as linalg

#最適化計算(最小値)用の関数
from scipy.optimize import minimize_scalar

#numpyのインポート
import numpy  as np

行列計算

In [4]:
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])

#行列式
print('行列式')
print(linalg.det(matrix))

行列式
-4.0


In [5]:
#逆行列
print('逆行列')
print(linalg.inv(matrix))

逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [7]:
#行列と逆行列の積＝単位行列
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#固有値と固有ベクトル
eig_value, eig_vector = linalg.eig(matrix)

print('固有値')
print(eig_value)
print('固有ベクトル')
print(eig_vector)

固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[ 0.57735027 -0.81649658  0.42755853]
 [ 0.57735027  0.40824829 -0.81618716]
 [ 0.57735027  0.40824829  0.38862863]]


ニュートン法

In [9]:
#関数の定義(f(x)=x^2+2x+1)
def my_function(x):
    return (x**2 + 2*x +1)

In [11]:
my_function(0)

1

In [10]:
#ニュートン法(近似値計算)の読み込み
from scipy.optimize import newton

#計算実行
print(newton(my_function, 0))

-0.9999999852953906


In [12]:
#f(x)の最小値を求める(Brent法)
print(minimize_scalar(my_function, method = 'Brent'))

     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002
