In [1]:
#ライブラリの読み込み
import numpy as np
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

%precision 3

#可視化用
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
sns.set()
%matplotlib inline

In [2]:
#配列の作成
sample_array = np.arange(10)
print('sample_array:',sample_array)

sample_array: [0 1 2 3 4 5 6 7 8 9]


In [3]:
#スライスを用いて前5つを抽出
sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4]


In [4]:
#sample_array_sliceの3文字目までは10で置換
sample_array_slice[0:3] = 10
print(sample_array_slice)

#注)オリジナルのリストも置換されてしまう！(参照しているため。コピーする必要がある)
print('sample_array:',sample_array)

[10 10 10  3  4]
sample_array: [10 10 10  3  4  5  6  7  8  9]


In [5]:
#sample_arrayをコピーする(np.copy)
sample_array_copy = np.copy(sample_array)
print('sample_array_copy:',sample_array_copy)

sample_array_copy[0:3] = 20
print('sample_array_copy:',sample_array_copy)

#コピーするとオリジナルのリストは置換されない。(コピーしたものを参照しているため)
print('sample_array:',sample_array)

sample_array_copy: [10 10 10  3  4  5  6  7  8  9]
sample_array_copy: [20 20 20  3  4  5  6  7  8  9]
sample_array: [10 10 10  3  4  5  6  7  8  9]


In [6]:
#bool index参照(条件抽出)

#データの準備(名前の配列とデータの配列)
sample_names = np.array(['a','b','c','d','a'])

np.random.seed(0)
data = np.random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [7]:
#真偽の判定
sample_names == 'a'

array([ True, False, False, False,  True])

In [8]:
#条件抽出(sample_names=='a'が0番目と4番目でTrueなので、dataのindexが0と4のデータを抽出する)
data[sample_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [9]:
#条件制御(numpy.whereを使うと、2つのデータX,Yの要素を条件で抽出できる)

#条件制御のために、ブールの配列を作成
cond_data = np.array([True,True,False,False,True])

#配列 x_array,y_array を作成
x_array = np.array([1,2,3,4,5])
y_array = np.array([100,200,300,400,500])

#条件制御実行
print(np.where(cond_data,x_array,y_array))

[  1   2 300 400   5]


In [10]:
#重複の削除
np.unique(cond_data)

array([False,  True])

In [11]:
#ユニバーサル関数:全ての要素に関数を適用できる機能
sample_data = np.arange(10)
print('元のデータ:',sample_data)
print('全ての要素の平方根:',np.sqrt(sample_data))
print('全ての要素のネイピア指数関数:',np.exp(sample_data))

元のデータ: [0 1 2 3 4 5 6 7 8 9]
全ての要素の平方根: [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
全ての要素のネイピア指数関数: [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [12]:
#最小、最大、平均、合計の計算

#0から8までの数を3行3列の行列にする
sample_multi_array_detail = np.arange(9).reshape(3,3)
print(sample_multi_array_detail)

print('最小値:',sample_multi_array_detail.min())
print('最大値:',sample_multi_array_detail.max())
print('平均値:',sample_multi_array_detail.mean())
print('合計:',sample_multi_array_detail.sum())

#行列を指定して合計値を求める
print('行の合計:',sample_multi_array_detail.sum(axis=1))
print('列の合計:',sample_multi_array_detail.sum(axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値: 0
最大値: 8
平均値: 4.0
合計: 36
行の合計: [ 3 12 21]
列の合計: [ 9 12 15]


In [13]:
#真偽値の配列関数
cond_data = np.array([True,True,False,False,True])

print('Trueが少なくとも1つあるかどうか:',cond_data.any())
print('全てTrueかどうか:',cond_data.all())

#※np.any(cond_data)、np.all(cond_data)でも可

Trueが少なくとも1つあるかどうか: True
全てTrueかどうか: False


In [16]:
#条件に一致する要素の個数を調べる
sample_multi_array_datal = np.arange(9).reshape(3,3)
print(sample_multi_array_datal)

print('5より大きい数字がいくつあるのか:',(sample_multi_array_datal>5).sum())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5より大きい数字がいくつあるのか: 3


In [17]:
#対角成分の計算
sample_multi_array_datal = np.arange(9).reshape(3,3)
print(sample_multi_array_datal)

print('対角成分:',np.diag(sample_multi_array_datal))
print('対角成分の和:',np.trace(sample_multi_array_datal))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
対角成分: [0 4 8]
対角成分の和: 12


配列操作とブロードキャスト

In [18]:
#再形成(行列の次元を変えること)
sample_array = np.arange(10)
print(sample_array)

sample_array2 = sample_array.reshape(2,5)
print(sample_array2)

print(sample_array2.reshape(5,2))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#データの用意
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
print(sample_array3)
print(sample_array4)

In [23]:
#データの結合

#行方向に結合。axisに0を指定
print(np.concatenate([sample_array3,sample_array4],axis=0))
#行方向の結合はvstackを使っても可能
print(np.vstack((sample_array3,sample_array4)))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
#列方向に結合。axisに1を指定
print(np.concatenate([sample_array3,sample_array4],axis=1))
#列方向の結合はhstackを使っても可能
print(np.hstack((sample_array3,sample_array4)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [26]:
#配列の分割
#結合
sample_array_vstack = np.vstack((sample_array3,sample_array4))
print(sample_array_vstack)
#分割(3つに分割し、first,second,thirdという3つの変数に代入)
first,second,third = np.split(sample_array_vstack,[1,3])

print('first')
print(first)
print('second')
print(second)
print('second[0]')
print(second[0])
print('third')
print(third)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
first
[[1 2 3]]
second
[[4 5 6]
 [7 8 9]]
second[0]
[4 5 6]
third
[[10 11 12]]


In [27]:
#繰り返し処理(repeatを使うと指定した回数だけ繰り返されて生成される)
first.repeat(5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [29]:
#ブロードキャスト
print(sample_array)
sample_array + 3
#上記は配列+配列でないので計算できないが、numpyは自動でnp.array[(3,3,3,…)]のように計算する。
#これをブロードキャストという。

[0 1 2 3 4 5 6 7 8 9]


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])